---
  all: 
    hosts:
      paylessbanners.com
#      airgapped.io 
#      wastewaterdesigns.com

    vars:
      sshd_pam: yes
      ansible_port: 22
      ansible_user: stader
      ansible_password: Tennal12$A
      ansible_sudo_pass: Tennal12$A
      ansible_ssh_pass: Tennal12$A
#      ansible_become_password: Tennal12$A
#      ansible_sudo_pass: Tennal12$A
#      ansible_password: Tennal12$A
#      ansible_port: 22

...
